plugins:
  - jekyll-archives-v2
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-get-json
  - jekyll-jupyter-notebook
  - jekyll-link-attributes
  - jekyll-minifier
  - jekyll-paginate-v2
  - jekyll-regex-replace
  - jekyll-scholar
  - jekyll-sitemap
  - jekyll-tabs
  - jekyll-terser
  - jekyll-toc
  - jekyll-twitter-plugin
  - jemoji
  - classifier-reborn

jekyll_imagemagick:
  enabled: false

external_sources: []

third_party_libraries: {}
